"""added sex column

Revision ID: a34de529b38e
Revises: efceb59e9de1
Create Date: 2018-11-06 23:42:02.704005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34de529b38e'
down_revision = 'efceb59e9de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mytable1', sa.Column('sex', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mytable1', 'sex')
    # ### end Alembic commands ###
